name: Build and Publish image to Docker Hub

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag neolinux/hamdashboard:latest
    - name: push image to docker hub
      run: |
        docker login -u neolinux -p ${{ secrets.DOCKER_HUB_TOKEN }}
        docker push neolinux/hamdashboard:latest
